<?php


use Phinx\Seed\AbstractSeed;

class FiListTypeSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run()
    {
        $this->query("TRUNCATE fi_list");
$query = "INSERT INTO `fi_list` (`id`, `name`) VALUES
(1, '1st Choice Savings and CU'),
(2, 'Accent CU'),
(3, 'Adjala CU'),
(4, 'ADS Canadian Bank'),
(5, 'Affinity CU 2013'),
(6, 'Agassiz CU'),
(7, 'Airline Financial CU'),
(8, 'Aldergrove CU'),
(9, 'Alliance CU'),
(10, 'Altona CU'),
(11, 'Apex CU'),
(12, 'Arborg CU'),
(13, 'Assiniboine CU'),
(14, 'AST Trust Company (Canada)'),
(15, 'Astra CU'),
(16, 'Austin CU'),
(17, 'AWCCU Financial'),
(18, 'B2B Bank'),
(19, 'B2B Trustco'),
(20, 'Bank of Montreal'),
(21, 'Bank of Nova Scotia '),
(22, 'Bank of Nova Scotia Trust Company '),
(23, 'Battle River CU'),
(24, 'Bay CU'),
(25, 'Beaumont CU'),
(26, 'Beautiful Plains CU'),
(27, 'Belgian CU'),
(28, 'Bengough CU'),
(29, 'Biggar and District CU'),
(30, 'BlueShore Financial CU'),
(31, 'BMO Trust Company'),
(32, 'BNY Trust Company of Canada'),
(33, 'Bow Valley CU'),
(34, 'Bridgewater Bank'),
(35, 'Bruno Savings and CU '),
(36, 'Buduchnist CU'),
(37, 'Buffalo CU'),
(38, 'Bulkley Valley CU'),
(39, 'Caisse Horizon CU'),
(40, 'Caisse populaire acadienne ltÃ©e (UNI)'),
(41, 'Cambrian CU'),
(42, 'Canada Trust Company'),
(43, 'Canadian Imperial Bank of Commerce'),
(44, 'Canadian Tire Bank'),
(45, 'Canadian Western Bank'),
(46, 'Canadian Western Trust Company'),
(47, 'Capital City Savings and CU'),
(48, 'Carpathia CU'),
(49, 'Casera CU'),
(50, 'CCEC CU'),
(51, 'Central 1 CU'),
(52, 'Central 1 Trust Company'),
(53, 'Chinook CU'),
(54, 'Churchbridge CU'),
(55, 'CIBC Mellon Trust Company'),
(56, 'CIBC Trust Corporation'),
(57, 'Cidel Trust Company'),
(58, 'Citizens Trust Company'),
(59, 'Civic CU'),
(60, 'Coast Capital Savings Federal CU'),
(61, 'Coast Capital Savings Federal CU'),
(62, 'Coastal Community CU'),
(63, 'Columbia Valley CU'),
(64, 'Common Wealth CU'),
(65, 'Community CU'),
(66, 'Community Savings CU'),
(67, 'Community Trust Company'),
(68, 'Compensation Employees CU'),
(69, 'Computershare Trust Company of Canada'),
(70, 'Comtech Fire CU'),
(71, 'Concentra Trust'),
(72, 'CONEXUS CU 2006'),
(73, 'Copperfin CU'),
(74, 'Cornerstone CU Financial Group '),
(75, 'Creative Arts Savings & CU '),
(76, 'Creston & District CU'),
(77, 'Crocus CU'),
(78, 'Crossroads CU'),
(79, 'Crosstown CU'),
(80, 'CS Alterna Bank'),
(81, 'Cypress CU '),
(82, 'Cypress River CU'),
(83, 'Dauphin Plains CU'),
(84, 'Delisle CU '),
(85, 'Desjardins Trust Inc.'),
(86, 'Diamond North CU'),
(87, 'DirectCash Bank'),
(88, 'Dodsland and District CU '),
(89, 'DUCA Financial Services CU '),
(90, 'Dufferin CU'),
(91, 'Dundalk District CU'),
(92, 'Duo Bank of Canada'),
(93, 'Earl Grey CU '),
(94, 'East Kootenay Community CU'),
(95, 'Eckville District Savings and CU'),
(96, 'Edam CU '),
(97, 'Edson Savings and CU'),
(98, 'Education CU'),
(99, 'Effort Trust Company '),
(100, 'Entegra CU'),
(101, 'Equitable Bank'),
(102, 'Equitable Trust'),
(103, 'Equity CU'),
(104, 'Erickson CU'),
(105, 'Eriksdale CU'),
(106, 'Exchange Bank of Canada'),
(107, 'Fiduciary Trust Company of Canada'),
(108, 'Finnish CU'),
(109, 'First CU'),
(110, 'First Nations Bank of Canada'),
(111, 'First West CU'),
(112, 'FirstOntario CU'),
(113, 'Flin Flon CU'),
(114, 'Foam Lake Savings and CU '),
(115, 'Fort York Community CU'),
(116, 'Frontline CU'),
(117, 'Ganaraska CU'),
(118, 'General Bank of Canada'),
(119, 'General Trust Corporation of Canada (In Liquidation)'),
(120, 'Gimli CU'),
(121, 'Grand Forks District Savings CU'),
(122, 'Grandview CU'),
(123, 'Greater Vancouver Community CU'),
(124, 'Haventree Bank'),
(125, 'Health Care CU'),
(126, 'Healthcare and Municipal Employees CU'),
(127, 'Heartland CU'),
(128, 'Heritage CU'),
(129, 'Heritage Savings & CU Inc.'),
(130, 'Home Bank'),
(131, 'Home Trust Company'),
(132, 'HomeEquity Bank'),
(133, 'Horizon CU'),
(134, 'HSBC Trust Company (Canada)'),
(135, 'Industrial Alliance Trust Inc.'),
(136, 'Inglewood Savings and CU'),
(137, 'Innovation CU'),
(138, 'Integris CU'),
(139, 'Interior Savings CU'),
(140, 'Investors Group Trust Co. Ltd.'),
(141, 'Kawartha CU'),
(142, 'Kerrobert CU '),
(143, 'Key Savings + CU'),
(144, 'Khalsa CU'),
(145, 'Kindred CU'),
(146, 'Kingston Community CU'),
(147, 'Kootenay Savings CU'),
(148, 'Korean (Toronto) CU'),
(149, 'Korean Catholic Church CU'),
(150, 'L.I.U.N.A. Local 183 CU'),
(151, 'La Salle CU'),
(152, 'Ladysmith & District CU'),
(153, 'Lafleche CU '),
(154, 'Lake View CU'),
(155, 'Lakeland CU'),
(156, 'Laurentian Bank of Canada'),
(157, 'Laurentian Trust of Canada Inc.'),
(158, 'LBC Trust'),
(159, 'Legacy Private Trust'),
(160, 'LeRoy CU '),
(161, 'Libro CU'),
(162, 'Luminus Financial Services and CU'),
(163, 'Luseland CU '),
(164, 'Macklin CU '),
(165, 'Macleod Savings and CU'),
(166, 'Mainstreet CU'),
(167, 'Manulife Bank of Canada'),
(168, 'Manulife Trust Company'),
(169, 'MD Private Trust Company'),
(170, 'Member Savings CU'),
(171, 'Minnedosa CU'),
(172, 'Momentum CU'),
(173, 'Montreal Trust Company of Canada'),
(174, 'Motor City Community CU'),
(175, 'Motus Bank'),
(176, 'Mount Lehman CU'),
(177, 'Mountain View CU'),
(178, 'Moya Financial CU Limited'),
(179, 'Natcan Trust Company'),
(180, 'National Bank of Canada'),
(181, 'National Trust Company'),
(182, 'Nelson & District CU'),
(183, 'New Community CU'),
(184, 'Niverville CU'),
(185, 'North Peace Savings and CU'),
(186, 'North Valley CU'),
(187, 'North Winnipeg CU'),
(188, 'Northern Birch CU'),
(189, 'Northern CU'),
(190, 'Northern Savings CU'),
(191, 'Northern Trust Company, Canada'),
(192, 'Oak Bank CU'),
(193, 'Oak Trust Company'),
(194, 'Ontario Educational CU'),
(195, 'Ontario Provincial Police Association CU'),
(196, 'Oshawa Community CU'),
(197, 'Osoyoos CU'),
(198, 'Ottawa Police CU'),
(199, 'Pace Savings & CU'),
(200, 'Parama CU'),
(201, 'Peace Hills Trust Company'),
(202, 'PenFinancial CU'),
(203, 'Peoples Bank of Canada'),
(204, 'Peoples Trust Company'),
(205, 'Pincher Creek CU'),
(206, 'Plainsview CU'),
(207, 'Portage CU'),
(208, 'Prairie Centre CU'),
(209, 'Prairie Pride CU'),
(210, 'Prospera CU'),
(211, 'Quinte First CU'),
(212, 'Radius CU '),
(213, 'Rapport CU'),
(214, 'Raymore Savings and CU '),
(215, 'RBC Investor Services Trust'),
(216, 'Resurrection CU'),
(217, 'Revelstoke CU'),
(218, 'RFA Bank of Canada (BC)'),
(219, 'Riverton CU'),
(220, 'Roblin CU'),
(221, 'Rockglen-Killdeer CU '),
(222, 'Rocky CU'),
(223, 'Rogers Bank'),
(224, 'Rosenort CU'),
(225, 'Royal Bank of Canada'),
(226, 'Royal Trust Company (The)'),
(227, 'Royal Trust Corporation of Canada'),
(228, 'Salmon Arm Savings and CU'),
(229, 'Sandhills CU '),
(230, 'Sandy Lake CU'),
(231, 'Sanford CU'),
(232, 'Saskatoon City Employees CU'),
(233, 'Servus CU'),
(234, 'Sharons CU'),
(235, 'Smiths Falls Community CU'),
(236, 'South Interlake CU'),
(237, 'Southwest Regional CU'),
(238, 'Spruce CU'),
(239, 'St. Gregor CU, '),
(240, 'St. Stanislaus-St. Casimirâ€™s Polish Parishes CU'),
(241, 'Stabilization Central CU of BC'),
(242, 'Starbuck CU'),
(243, 'State Street Trust Company Canada'),
(244, 'Ste.Rose CU'),
(245, 'Steinbach CU'),
(246, 'Stoughton CU '),
(247, 'Strathclair CU'),
(248, 'Sudbury CU'),
(249, 'Summerland & District CU'),
(250, 'Sun Life Financial Trust Inc.'),
(251, 'Sunshine Coast CU'),
(252, 'Swan Valley CU'),
(253, 'Synergy CU '),
(254, 'Taiwanese-Canadian (Toronto) CU'),
(255, 'Talka CU Limited'),
(256, 'Tandia Financial CU'),
(257, 'Tangerine Bank'),
(258, 'TCU Financial Group CU'),
(259, 'The Energy CU'),
(260, 'The Police CU'),
(261, 'Thorold Community CU'),
(262, 'Toronto Municipal Employeesâ€™ CU'),
(263, 'Toronto-Dominion Bank '),
(264, 'TSX Trust Company'),
(265, 'Turtleford CU '),
(266, 'Ukrainian CU'),
(267, 'Union Bay CU'),
(268, 'United Employees CU'),
(269, 'Unity CU '),
(270, 'V.P. CU'),
(271, 'Valiant Trust Company'),
(272, 'Vancity Community Investment Bank'),
(273, 'Vancouver City Savings CU'),
(274, 'Vancouver Firefighters CU'),
(275, 'Vanguard CU'),
(276, 'VantageOne CU'),
(277, 'Vermilion CU'),
(278, 'VersaBank'),
(279, 'Virden CU'),
(280, 'Wainwright CU'),
(281, 'Wealth One Bank of Canada'),
(282, 'Wetaskiwin CU'),
(283, 'Weyburn CU '),
(284, 'WFCU CU'),
(285, 'Williams Lake and District CU'),
(286, 'Winnipeg Police CU'),
(287, 'Your CU'),
(288, 'Your Neighbourhood CU'),
(289, 'Zag Bank'),
(290, 'G&F Financial CU');";

        $this->execute($query);
    }
}
