export const ADD_NEW_REQUEST = "ADD_NEW_REQUEST";
export const REMOVE_A_REQUEST = "REMOVE_A_REQUEST";
export const CLEAR_REQUEST = "CLEAR_REQUEST";
export const ADD_PREFFERED_COLLATERAL = "ADD_PREFFERED_COLLATERAL";
export const SET_SELECTED_FIS = "SET_SELECTED_FIS";
export const SET_REQUEST_SUMMARY = "SET_REQUEST_SUMMARY";
// request offers
export const CLEAR_REQUEST_OFFERS = "CLEAR_REQUEST_OFFERS";
export const REMOVE_A_REQUEST_OFFER = "REMOVE_A_REQUEST_OFFER";
export const ADD_NEW_REQUEST_OFFER = "ADD_NEW_REQUEST_OFFER";

// prime rate
export const SET_PRIME_RATES = "SET_PRIME_RATES";

// review Offers
export const SET_REVIEW_REQUEST_OFFERS = "SET_REVIEW_REQUEST_OFFERS";
// settlemnt date
export const SET_SETTLEMENT_DATE = "SET_SETTLEMENT_DATE";
// globalProducts
export const SET_GLOBAL_PRODUCTS = "SET_GLOBAL_PRODUCTS";
// history offers
export const SET_HISTORY_OFFERS = "SET_HISTORY_OFFERS";
export const SET_OFFER_ERRORS = "SET_OFFER_ERRORS";

export const UPDATE_SELECTED_OFFER_ENTRY = "UPDATE_SELECTED_OFFER_ENTRY";
