export const SET_ALL_SELECTED_REQUEST_OFFERS =
    "SET_ALL_SELECTED_REQUEST_OFFERS";
export const SET_PICKED_SELECTED_REQUEST_OFFERS =
    "SET_PICKED_SELECTED_REQUEST_OFFERS";
export const UPDATE_KEY_FOR_OFFERS = "UPDATE_KEY_FOR_OFFERS";

export const SET_ALL_SELECTED_REQUEST_OFFERS_RATES =
    "SET_ALL_SELECTED_REQUEST_OFFERS_RATES";
export const UPDATE_KEY_FOR_EARNED_RATES = "UPDATE_KEY_FOR_EARNED_RATES";

export const SET_CURRENT_OFFER_COUNTERS = "SET_CURRENT_OFFER_COUNTERS";
