export const SET_CAMPAIGN_SELECTED_PRODUCTS = "SET_CAMPAIGN_SELECTED_PRODUCTS";
export const SET_CAMPAIGN_SELECTED_PRODUCTS_IDS =
    "SET_CAMPAIGN_SELECTED_PRODUCTS_IDS";
export const UPDATE_CAMPAIGN_SELECTED_PRODUCTS_IDS =
    "UPDATE_CAMPAIGN_SELECTED_PRODUCTS_IDS";
export const UPDATE_CAMPAIGN_SELECTED_PRODUCTS_IDS_MANUAL =
    "UPDATE_CAMPAIGN_SELECTED_PRODUCTS_IDS_MANUAL";
export const SET_ALL_PRODUCTS_SELECTED = "SET_ALL_PRODUCTS_SELECTED";
export const UPDATE_SELECTED_PRODUCTS = "UPDATE_SELECTED_PRODUCTS";
export const UPDATE_SELECTED_PRODUCTS_MANUAL =
    "UPDATE_SELECTED_PRODUCTS_MANUAL";
export const UPDATE_SELECTED_PRODUCT_MAX = "UPDATE_SELECTED_PRODUCT_MAX";
export const UPDATE_SELECTED_PRODUCT_MIN = "UPDATE_SELECTED_PRODUCT_MAX";
export const UPDATE_SELECTED_PRODUCT_RATE = "UPDATE_SELECTED_PRODUCT_MAX";
export const UPDATE_SELECTED_PRODUCT_TERMLENGTH = "UPDATE_SELECTED_PRODUCT_MAX";
export const UPDATE_SELECTED_PRODUCT_NAME = "UPDATE_SELECTED_PRODUCT_NAME";

export const UPDATE_SELECTED_PRODUCT_ENTRY = "UPDATE_SELECTED_PRODUCT_ENTRY";
export const SET_ACTIVE_PRODUCT_LIST = "SET_ACTIVE_PRODUCT_LIST";

export const DESELECT_ALL_ACTIVE_PRODUCTS = "DESELECT_ALL_ACTIVE_PRODUCTS";
